"""Add api_key to mcp_servers

Revision ID: d899ad62f8f7
Revises: 5c58b8eb1f06
Create Date: 2025-09-26 15:18:11.191858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd899ad62f8f7'
down_revision: Union[str, Sequence[str], None] = '5c58b8eb1f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
